<?php

namespace AppBundle\Repository;

/**
 * IngredientStepJoinRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IngredientStepJoinRepository extends \Doctrine\ORM\EntityRepository
{
}
