<?php

namespace AppBundle\Repository;

/**
 * IngredientTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IngredientTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
