<?php

namespace AppBundle\Repository;

/**
 * RecipeIngerientJoinRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecipeIngerientJoinRepository extends \Doctrine\ORM\EntityRepository
{
}
